src/menus/urls.py
from django.conf.urls import url


from .views import ( 
	ItemCreateView,
	ItemDetailView,
	ItemListView,
	ItemUpdateView	
	)



urlpatterns = [
    url(r'^(?P<pk>\d+)/$',ItemUpdateView.as_view(),name='detail'),
    #url(r'^(?P<pk>\d+)/edit/$',ItemUpdateView.as_view(),name='edit'),
    url(r'^$',ItemListView.as_view(),name="list"),
    url(r'^create/$',ItemCreateView.as_view(),name="create"),
]

src/muypicky/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.contrib.auth.views import LoginView

from django.contrib.auth.views import LogoutView

from menus.views import HomeView

from restaurants.views import (
	AboutView, 
	ContactView, 
	RestaurantView,
	RestaurantDetailView,
	RestaurantCreateView
	)

from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/', RegisterView.as_view(),name='register'),
    url(r'^login/', LoginView.as_view(),name='login'),
    url(r'^logout/', LogoutView.as_view(),name='logout'),
    url(r'^follow/', ProfileFollowToggle.as_view(),name='follow'),
    url(r'^$',HomeView.as_view()),
    url(r'^restaurants/', include('restaurants.urls',namespace='restaurants')),
    url(r'^items/', include('menus.urls',namespace='menus')),
    url(r'^about/$',AboutView.as_view(),name='about'),
    url(r'^u/', include('profiles.urls',namespace='profiles')),
    url(r'^contact/$',ContactView.as_view(),name='contact'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view,name="activate"),
]

src/menus/models.py
from django.conf import settings
from django.db import models

from django.core.urlresolvers import reverse


from restaurants.models import RestaurantLocation

class Item(models.Model):
	user 		= 	models.ForeignKey(settings.AUTH_USER_MODEL)
	restaurant	= 	models.ForeignKey(RestaurantLocation)

	name 		= 	models.CharField(max_length=120)
	contents 	= 	models.TextField(help_text='Separate each Item by comma')
	excludes 	= 	models.TextField(blank = True, null=True, help_text='Separate each Item by comma')
	public 		= 	models.BooleanField(default=True)
	timestamp 	= 	models.DateTimeField(auto_now_add=True)
	updated 	=	models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['-updated','-timestamp']

	def get_absolute_url(self):
		return reverse("menus:detail", kwargs = { "pk":self.pk})

	def get_content(self):
		return self.contents.split(",")

	def get_excludes(self):
		return self.excludes.split(",")

src/menus/forms.py
from django import forms

from .models import Item
from restaurants.models import RestaurantLocation

class ItemForm(forms.ModelForm):
	class Meta:
		model 	= 	Item
		fields 	=	[
				'restaurant',
				'name',
				'contents',
				'excludes',
				'public'
			]

	def __init__(self,user=None, *args, **kwargs):
		print(user)
		super(ItemForm, self).__init__(*args,**kwargs)
		self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)

src/menus/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import View
from django.views.generic import CreateView
from django.views.generic import UpdateView

from .models import Item

from .forms import ItemForm


class HomeView(View):
	def get(self, request, *args, **kwargs):
		print("in actual home view")
		if not request.user.is_authenticated():
			print("User not authenticated")
			return render(request, "home.html", {})

		user = request.user
		if_following_user_ids = [ x.user.id for x in user.is_following.all() ]
		qs = Item.objects.filter(user__id__in=if_following_user_ids, public=True)

		return render(request, "menus/home-feed.html", {'object_list':qs})


class ItemListView(LoginRequiredMixin, ListView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)


class ItemDetailView(LoginRequiredMixin, DetailView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)


class ItemCreateView(LoginRequiredMixin, CreateView):
	template_name = 'forms.html'
	form_class 	=	ItemForm
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

	def form_valid(self,form):
		obj = form.save(commit=False)
		obj.user = self.request.user
		return super(ItemCreateView, self ).form_valid(form)

	def get_form_kwargs(self):
		kwargs = super(ItemCreateView,self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs 

	def get_context_data(self, *args, **kwargs):
		context 	= 	super(ItemCreateView, self).get_context_data(*args, **kwargs)
		context['title'] 	= 	"Create Item"
		return context


class ItemUpdateView(LoginRequiredMixin,  UpdateView):
	template_name = 'menus/detail-update.html'
	form_class 	=	ItemForm
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

	def get_context_data(self, *args, **kwargs):
		context 	= 	super(ItemUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] 	= 	"Update Item"
		return context

	def get_form_kwargs(self):
		kwargs = super(ItemUpdateView,self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs 

src/menus/templates/menus/detail-update.html
{% extends "base.html" %}
<title>{% block head_title %} Items | {{ block.super }}  {% endblock %}</title>

{% block content %}
<h1> Menu Items </h1>

<ul>
{{ form.instance.name }}
 		<li> 


 		{% if form.instance.contents %}
 		Contents
 		<ul>
	 		{% for item in form.instance.get_content %}
			 		<li>
			 			{{ item }}
			 		</li>
 			{% endfor %}
 		</ul>
 		{% endif %}

 		 {% if form.instance.excludes %}
 		Excludes

 		<ul>
	 		{% for item in form.instance.get_excludes %}
			 		<li>
			 			{{ item }}
			 		</li>
 			{% endfor %}
 		</ul>
 		{% endif %}
 

 		  </li>

</ul>
<hr/>
<h3> Make Changes </h3>
	{% include 'snippets/form-snippet.html' with form=form %}
{% endblock %}

src/menus/templates/menus/home-feed.html
{% extends 'base.html' %}

{% block content %}

<ul>
	{% for obj in object_list %}
 		<li> 


 	<div class="row">
				<div class="col-sm-12"> 
				<h4>
				<a href="{% url 'profiles:detail' username=obj.user.username  %}"> {{ obj.user.username }} </a><br/>
				 <a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a> </h4>
				<p> {{ obj.restaurant.title }} ||   {{ obj.restaurant.location }} || {{ obj.restaurant.category }}   </p>
				<div class='thumbnail'>
					<ul>
				
						<ul>
								<b> {{ obj.name }} </b></br>
								{% for ing in obj.get_content %}

								<a href='{{ request.path }}?q={{ing}}'> {{ ing }} </a>

								{% endfor %}
						</ul>
					</ul>
					</div>
				</div>
			</div>

 		  </li>
	{% endfor %}
</ul>
{%	endblock %}

src/menus/templates/menus/item_detail.html
{% extends "base.html" %}
<title>{% block head_title %} Items | {{ block.super }}  {% endblock %}</title>

{% block content %}
<h1> Menu Items </h1>


<ul>
{{ object.name }}
 		<li> 


 		{% if object.contents %}
 		Contents
 		<ul>
	 		{% for item in object.get_content %}
			 		<li>
			 			{{ item }}
			 		</li>
 			{% endfor %}
 		</ul>
 		{% endif %}

 		 {% if object.excludes %}
 		Excludes

 		<ul>
	 		{% for item in object.get_excludes %}
			 		<li>
			 			{{ item }}
			 		</li>
 			{% endfor %}
 		</ul>
 		{% endif %}
 

 		  </li>

</ul>
{% endblock %}

src/menus/templates/menus/item_list.html
{% extends "base.html" %}
<title>{% block head_title %} Items | {{ block.super }}  {% endblock %}</title>

{% block content %}
<h1> Menu Items </h1>

<ul>
	{% for obj in object_list %}
 		<li> <a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a>


 		{% if obj.contents %}
 		Contents
 		<ul>
	 		{% for item in obj.get_content %}
			 		<li>
			 			{{ item }}
			 		</li>
 			{% endfor %}
 		</ul>
 		{% endif %}

 		 {% if obj.excludes %}
 		Excludes

 		<ul>
	 		{% for item in obj.get_excludes %}
			 		<li>
			 			{{ item }}
			 		</li>
 			{% endfor %}
 		</ul>
 		{% endif %}
 

 		  </li>
	{% endfor %}
</ul>
{% endblock %}