src/menus/urls.py
from django.conf.urls import url


from .views import ( 
	ItemCreateView,
	ItemDetailView,
	ItemListView,
	ItemUpdateView	
	)



urlpatterns = [
    url(r'^(?P<pk>\d+)/$',ItemUpdateView.as_view(),name='detail'),
    #url(r'^(?P<pk>\d+)/edit/$',ItemUpdateView.as_view(),name='edit'),
    url(r'^$',ItemListView.as_view(),name="list"),
    url(r'^create/$',ItemCreateView.as_view(),name="create"),
]

src/muypicky/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.contrib.auth.views import LoginView

from django.contrib.auth.views import LogoutView

from menus.views import HomeView

from restaurants.views import (
	AboutView, 
	ContactView, 
	RestaurantView,
	RestaurantDetailView,
	RestaurantCreateView
	)

from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/', RegisterView.as_view(),name='register'),
    url(r'^login/', LoginView.as_view(),name='login'),
    url(r'^logout/', LogoutView.as_view(),name='logout'),
    url(r'^follow/', ProfileFollowToggle.as_view(),name='follow'),
    url(r'^$',HomeView.as_view()),
    url(r'^restaurants/', include('restaurants.urls',namespace='restaurants')),
    url(r'^items/', include('menus.urls',namespace='menus')),
    url(r'^about/$',AboutView.as_view(),name='about'),
    url(r'^u/', include('profiles.urls',namespace='profiles')),
    url(r'^contact/$',ContactView.as_view(),name='contact'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view,name="activate"),
]

src/restaurants/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.contrib.auth.views import LoginView

from django.contrib.auth.views import LogoutView

from restaurants.views import ( 
	RestaurantView,
	RestaurantDetailView,
	RestaurantCreateView,
	RestaurantUpdateView
	)


urlpatterns = [
    url(r'^$',RestaurantView.as_view(), name="listview"),
    url(r'^restaurantsc/$',RestaurantCreateView.as_view(),name="create"),
    #url(r'^(?P<slug>\w+)$',RestaurantView.as_view(),name='rlv'),
    #url(r'^(?P<slug>[\w-]+)/$',RestaurantDetailView.as_view(),name='rdlv'),
    url(r'^(?P<slug>[\w-]+)/$',RestaurantUpdateView.as_view(),name='edit'),
]

src/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

src/templates/snippets/form-snippet.html
{{ form.errors }}
<form method="POST"> {% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> Save</button>
</form>

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class="container">
<h1> Muypicky home </h1>
<a href="/"> Home </a>
<a href="{% url 'about' %}"> About </a>
<a href="{% url 'contact' %}"> Contact </a>

{% if request.user.is_authenticated %}
	<a href="{% url 'restaurants:listview' %}"> Restaurants </a>
	<a href="{% url 'menus:list' %}"> Items </a>
{% endif %}


<a href="{% url 'logout' %}"> Logout </a>

<div class="container">